INSERT INTO PLATFORMS (PLATFORM_ID, PLATFORM_NAME)
VALUES
     (1, 'PLATFORM_ONE'),
     (2, 'PLATFORM_TWO'),
     (3, 'PLATFORM_THREE');

INSERT INTO APPLICATIONS (APP_ID, APP_NAME)
VALUES
    (1, 'APPLICATION_ONE'),
    (2, 'APPLICATION_TWO'),
    (3, 'APPLICATION_THREE');

INSERT INTO ORGANIZATIONS (ORG_ID, ORG_NAME)
VALUES
    (1, 'ORGANIZATION_ONE'),
    (2, 'ORGANIZATION_TWO'),
    (3, 'ORGANIZATION_THREE');