DROP TABLE IF EXISTS PLATFORMS;

CREATE TABLE PLATFORMS (
    PLATFORM_ID INT AUTO_INCREMENT  PRIMARY KEY,
    PLATFORM_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS APPLICATIONS;

CREATE TABLE APPLICATIONS (
    APP_ID INT AUTO_INCREMENT  PRIMARY KEY,
    APP_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS ORGANIZATIONS;

CREATE TABLE ORGANIZATIONS (
    ORG_ID INT AUTO_INCREMENT  PRIMARY KEY,
    ORG_NAME VARCHAR(255)
);